### ISSUE TITLE
Replace the Gpad microcontroller, ATMEGA328P, with the ESP32 module 

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#107]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 After inhereting the schematic of the GPAD, we used another microcontroller, ESP32, and now both microcontrollers exist. 
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Remove old microcontroller, ATMEGA328P.
 

**Additional context**
_Add any other context or screenshots about the feature request here._
<img width="700" alt="image" src="https://github.com/user-attachments/assets/29b82db6-8e03-4985-84d8-ee1049f27350" />

**Comment by ForrestErickson** [comment]
Done.
Closing issue.
