### ISSUE TITLE
Reassign UART1 GPIO pins

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#112]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 After changing the UART1 GPIO pins we should reassign the pins on the ESP32 
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 Assign GPIO 2 as TX1 and GPIO 15 as RX1 
 (Rename GPIO 9 and 10.)

**Additional context**
_Add any other context or screenshots about the feature request here._
<img width="344" alt="image" src="https://github.com/user-attachments/assets/97b1b36b-63f5-4e90-b1a3-802d5cbb1ba7" />

**Comment by ForrestErickson** [comment]
Done on GPAD_API Version 0.23.
Note that there is a #if !defined (HMWK) which is removing the setup in the code which must go away once we have real KRAKE PCBs.

CC:
@RobertLRead
