### ISSUE TITLE
LCD Mounting Nut Inadequate Clearance For Nut Driver

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#119]
**Describe the Failure / Bug**
_A clear and concise description of what the failure / bug is. Describe the problem NOT the fix._

Short Summary of the expected behavior: I expect to be able to drive the LCD mounting screw nuts tight with a nut driver. 
Short Summary of the buggy behavior:  There is interference on one or more nuts.

From the GPAD,
The mounting nut near the three terminal regulator.
![image](https://github.com/user-attachments/assets/cbd46b63-e27f-4091-ac4c-0e43e35ea434)
 
The nut driver in interference with the three terminal regulator
![image](https://github.com/user-attachments/assets/5091336b-1077-4459-8299-3a5e854b8797)

**Additional context**
_Add any other context about the problem here._

 The outer diameter of a 1/4" Craftsman nut driver is 10mm. Need some clearance over that.

**Comment by nk25719** [comment]
This is a new footprint of the LCD, a new keep out at the four corners is added.


<img width="660" alt="image" src="https://github.com/user-attachments/assets/2f375522-0960-423d-be30-6a734075883c" />
