### ISSUE TITLE
Schematic and Firmware, Pin Names for Rotaray Encoder, RT_ENC_CLK, RT_ENC_DT, and nENTER 

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#120]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 I'm always frustrated when net names on schematics and firmware do not match.
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 
@nk25719 
Please modify the schematic with the net names on GPIO pins for the rotary encoder as per this example
![image](https://github.com/user-attachments/assets/ac8226c6-e960-4a96-a63d-00e48386feae)

@RobertLRead 
Please use these pin definitions above on the Firmware HAL.
See the subject line and the schematic screen shot.

**Comment by nk25719** [comment]
<img width="397" alt="image" src="https://github.com/user-attachments/assets/aaf9899c-75de-49dc-bacf-49d49ab904d1" />

the Rotary encoder datasheet does not use the DT CLK and SW pinnames 

https://www.lcsc.com/datasheet/lcsc_datasheet_1809200034_ALPSALPINE-EC11E18244AU_C202365.pdf

**Comment by nk25719** [comment]
Decided to use net names that reflects the names of the pins of the encoder instead of the net names suggested by this issue subject line.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0e56cf43-ca7f-4643-9e60-81084c074931" />
