### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#15]
We need to add Issue templates to the KRAKE repo. 

Here is a screenshot of the issue template I added to one of my projects. 

<img width="944" alt="image" src="https://github.com/PubInv/krake/assets/133608369/a9923cd7-3197-4da4-a664-85abbaf0ce56">

**Comment by ForrestErickson** [comment]
Yes I think so too.

**Comment by nk25719** [comment]
@RobertLRead we were unable to add templates to the issues because the option to add issue templates is not available to us. We have the templates ready to be added but need help with the process.

**Comment by nk25719** [comment]
Done as requested. 

Closing...
