### ISSUE TITLE
Prototype a Rotary Encoder

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#20]
**Is your feature request related to a problem? Please describe.**
A controller to navigate through the functions of Krake

**Describe the solution you'd like**
adding an encoder to mocking krake 

**Describe alternatives you've considered**

**Additional context**

**Comment by nk25719** [comment]
https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/issues/42

**Comment by ForrestErickson** [comment]
@nk25719 has created firmware at:
krake\Firmware\factoryTest\Rotarty Encoder\RotaryEncoderTest

This firmware interfaces the encoder at the following pins:
> // Define the GPIO pins for CLK, DT, and SW
> const int CLK = 14;   // Connected to the CLK pin of the encoder
> const int DT = 26;    // Connected to the DT pin of the encoder
> const int SW = 25;    // Connected to the SW (Switch) pin of the encoder

**Comment by ForrestErickson** [comment]
This appears to be a duplicate to issue #5.

The information in this issue should be copied into #5 and this issue closed as a duplicate.

If we, the team, had been more diligent reviewing issues this duplicate might have been found earlier.  This is symptomatic of not using the project board and issues enough.

**Comment by ForrestErickson** [comment]
20241002 Lee copied the content from this issue into the older issue #5

**Comment by ForrestErickson** [comment]
Closing as duplicate

**Comment by ForrestErickson** [comment]
20241224 Done.
