### ISSUE TITLE
Make Wokwi Simulation

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#3]
To the extend possible make a Wokwi simulation of the Krake.

The following kits are available from Wokwi
![image](https://github.com/PubInv/krake/assets/5836181/6b6d1867-380a-40a9-a128-9542bb749e0d)

While none of these are pin for pin the same as the ESPkits (Node MCU?) which Nagham and Lee have there is likely to be something which can be wired as if the same.

Lee thinks we want the S2 kit.

**Comment by ForrestErickson** [comment]
Some documentation on Wokwi simulations of the ESP32 platform:
https://docs.wokwi.com/guides/esp32-wifi

There is a ESP32 HTTP IoT Server Example for Wokwi.com
https://wokwi.com/projects/320964045035274834

**Comment by nk25719** [comment]
link to Wokwi simulations of Krake: 


https://wokwi.com/projects/406034970467392513

> still processing the simulation..  // Status:  Incomplete

**Comment by ForrestErickson** [comment]
Although we can not simulate the WiFi connection with out a paid account a connection by SPI and UART could be some what simulated.  OR CAN IT?

**Item for brief team meeting discussion.**

**Comment by ForrestErickson** [comment]
@RobertLRead 
See the information above to be aware of the payment required for WiFi simulation in Wokwi..

At this time I think we can work with out the Wokwi because of the very usefully Hardware2 assembly Nagham designed.

Closing.
