### ISSUE TITLE
Write a User Manual for Krake

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#45]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 
Write a user manual for Krake
The sum of use cases.

**Comment by nk25719** [comment]
dublicated in issue #49 

closing.

**Comment by ForrestErickson** [comment]
Good catch.

**Comment by ForrestErickson** [comment]
Document at: https://docs.google.com/document/d/150WA6Mb1_SFOBmFc9qBpT5b-MqXb7ejaZbKIxUqaDBY/edit?tab=t.0#heading=h.wxbfbyr25edt
