### ISSUE TITLE
Add SPI Interface as Peripheral (Formerly Slave)

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#47]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
If the Krake™ is to be a replacement for the GPAD, it must be possible to be controlled by SPI interface just as the GPAD was.
The GPAD interface is a 5V logic level.
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 Add an SPI (Serial Peripheral Interface) to communicate with peripheral devices
Serial Peripheral Interface is a four wire  interface for bidirectional logic level connection from a Controller to a Peripherial.
In a system, the Krake™ is the peripheral.   Some other device is the SPI Controller. 
The SPI interface is so old that when it was defined logic levels were 5 Volt.
 
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

For the Poly Vent the 3.3 Volt Controller (ESP32) SPI interface was level shifted up to 5Volts for the GPAD. 
The same level shifting technique must be evaluated for the Krake™
 
**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by ForrestErickson** [comment]
### Reference Data sheet for ESP32 S2:
https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf
See section 3.4.2 Serial Peripheral Interface (SPI)

### To Do, Prototype SPI As Peripheral
Figure out which of the four SPI peripherals are available (not already in use) on the ESP32 Dev Kit we have. 
Prototype an SPI Peripheral (formerly Slave) system and control it with an SPI Controller (Formerly Master) and make

**Comment by ForrestErickson** [comment]
## To Do Review ESP32 S2 SPI Libraries
Here is one
https://github.com/hideakitai/ESP32SPISlave

## Random Nerd Tutorials ESP32 SPI Tutorial
https://randomnerdtutorials.com/esp32-spi-communication-arduino/

![image](https://github.com/user-attachments/assets/8d7007b5-50da-4d31-a333-3c2db04e87a4)

**Comment by ForrestErickson** [comment]
Added Robert to this issue.

@RobertLRead 
The GPAD firmware will need to be modified so that it can compile on both the UNO controller and the ESP32-S2. 
I am assuming a lot of #ifdefine ESP32-S2 else #ifdef Atmega328 will be required.

**Comment by ForrestErickson** [comment]
## SPI Pins on ESP32 DEV
Lee loaded and ran the Random Nerd Tutorials sketch to identify SPI pins on his ESP32-S2 Deve Kit 1
![image](https://github.com/user-attachments/assets/9e0858ad-2403-4122-abfe-ab1c19d309d5)

Bottom line
05:56:43.509 -> MOSI: 23
05:56:43.509 -> MISO: 19
05:56:43.509 -> SCK: 18
05:56:43.509 -> SS: 5

@nk25719 
Please review the MockingKrake for the availability of these pins and any conflict with existing pin usage and report to @RobertLRead  and @ForrestErickson

**Comment by ForrestErickson** [comment]
@nk25719 
Wiring two Homework2 assemblies together would be a prudent thing to do in a way that reflects the SPI buss connections we have put into the KRAKE schematic.

Then one device is programed as a Controller and one as a Peripheral to verify the hardware connection works.

In addition there should be a Peripheral Interrupt Request, a GPIO output on the Peripheral which goes into an input on the Controller to signal the Peripheral needs attention.  The  Peripheral Interrupt Request needs to be added to the GPAD schematic.

**Comment by nk25719** [comment]
changing the pin assignments of the SPI from 
<img width="280" alt="image" src="https://github.com/user-attachments/assets/fa07a13a-15ae-4077-97d4-ebfc8377753b">

GPIO26 - COPI
GPIO25 - SPI_SCK
GPIO 33 - nCS
GPIO32  - CIPO



To pins 
<img width="221" alt="image" src="https://github.com/user-attachments/assets/103d5949-0e58-4569-bb48-2baa7ad10493">

GPIO23 - COPI
GPIO19 -  CIPO
GPIO18 - SPI_SCK
GPIO5 - nCS

**Comment by ForrestErickson** [comment]
changing the pin assignments of the LIGHT signals
LIGHT2, LIGHT3 and LIGHT4

From:
![image](https://github.com/user-attachments/assets/5ddf79de-1c38-481e-ba5c-4b71a06cbe1d)

To:

**Comment by nk25719** [comment]
<img width="274" alt="image" src="https://github.com/user-attachments/assets/3f684602-528e-44c4-b6f0-9a767527dea4">


Changing Pin assignment 
S2 connection from GPIO 33 to GPIO 34 
Mute switch from GPIO 34 to GPIO 35

**Comment by nk25719** [comment]
Check issue #50 for latest updates for the SPI Interface.
