### ISSUE TITLE
SPI Buss Controler at 5V and the ESP32 at 3.3V May Fail 

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#50]
**Describe the Failure / Bug**
_A clear and concise description of what the failure / bug is. Describe the problem NOT the fix._

Short Summary of the expected behavior:  Connect an SPI Controller to and SPI Peripheral should not damage parts.

Short Summary of the buggy behavior:  5V controllers for example UNO may over voltage inputs on 3.3V Peripherals for example ESP32
 
Elementary explanation of voltage incompatibility and some level shifting solutions.

https://www.arrow.com/en/research-and-events/articles/using-a-level-shifter-to-integrate-different-voltage-signals

**Comment by nk25719** [comment]
<img width="407" alt="Screenshot 2024-11-16 124651" src="https://github.com/user-attachments/assets/7cf8cd45-abe6-4b19-9958-bb67cbd0ac10">

**Comment by ForrestErickson** [comment]
@nk25719 
Philips Semiconductor invented the I2C system.
A more detailed understanding of the MOSFET level shifter and the requirements of I2C is found in the Philips Semiconductor documentation. 
When you have time, see: https://cdn-shop.adafruit.com/datasheets/an97055.pdf

**Comment by ForrestErickson** [comment]
## Topics

- What is the depletion region of an PN Junction. See: https://en.wikipedia.org/wiki/Depletion_region
- What is a JFET and how does it work. (It works on the principles of a PN Junction). See: https://www.nutsvolts.com/magazine/article/fet_principles_and_circuits_part_1
- Then what are the additional features of the MOSFET over a JFET? See: https://www.tutorialspoint.com/difference-between-jfet-and-mosfet

The AI summary to the question, "how is a mosfet different from a JFET" is insightful too:

> ![image](https://github.com/user-attachments/assets/1a01cc90-fb53-4766-9648-468c762bd434)

**Comment by nk25719** [comment]
SPI interface with level shifters and ESD protection. 

<img width="468" alt="image" src="https://github.com/user-attachments/assets/dcdbac7d-b385-4b8c-8139-9b177c2d6706">
