### ISSUE TITLE
Krake has no Project Board

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#6]
I am not able to select a project when making a Krake Issue.

![image](https://github.com/PubInv/krake/assets/5836181/c8eb8fc8-204d-4246-b656-f1f75a4b5eef)

**Comment by RobertLRead** [comment]
@ForrestErickson did not have permission to use the Project. I have sent you an invitation. If you click on it, it may solved this problem.

**Comment by nk25719** [comment]
<img width="718" alt="image" src="https://github.com/PubInv/krake/assets/133608369/507b53ad-c8be-450f-896d-72b26e9081c1">    

> Added a Project Board.

**Comment by nk25719** [comment]
@ForrestErickson 
the project board is ready to be reviewd, and if the issue is solved we can move it to from IN REVIEW to DONE in KRAKE V1 backlog
