### ISSUE TITLE
Design Key Cap for Homework2 Switches

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#60]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 I want a key cap on the Homework2 assemblies to work with the EnclosureRevC
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
The key cap should fit over the switch key with a blind pocket (blind hole) some what shorter than the key is tall so that the key can be pressed.
Near the bottom of the key cap the outer size of the key should be larger  than the opening in the top. It should then reduce down to a size smaller than the hole for the keys in the top.  This will keep the key cap from falling out of the enclosure.
 
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
 
 Note the variety of 6mm Tach switches with different size and styles of keys.
 
![image](https://github.com/user-attachments/assets/5e1ae019-9b8e-4cbf-8046-790e0344b745)

Unfortunately the JLCPCB part number provides a drawing which does not specify a particular key size. 
![image](https://github.com/user-attachments/assets/fe055ad6-abfc-47a2-b2fe-0174186d4659)

When Lee measures the part he has on the Homework2 assemblies from JLCPCB the "H" dimension is 8.75mm

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by ForrestErickson** [comment]
Here is an OMRON part which probably matches our part with an "H" of 9mm.
B3F-1070, B3F-1072, B3F-1075, B3F-1072-G

![image](https://github.com/user-attachments/assets/0f83f336-973f-410e-a259-31e01e51b5be)

From Digikey I find and select at 3D model.
![image](https://github.com/user-attachments/assets/a65f88bb-dbaa-457a-b4e2-588ad630d102)

**Comment by ForrestErickson** [comment]
Note the Homework2 PWA does not have a 3D model for the switches.
![image](https://github.com/user-attachments/assets/30ce4798-865e-40ea-8b8a-21723fcba125)
and
![image](https://github.com/user-attachments/assets/dd659055-b33c-4f20-9f05-81e8ea4a53cc)

If we could fix this path perhaps we would have the required file.

## Temporary , test, Solution
However the Omron downloaded STEP file above can be added to a single part in the PCB.
![image](https://github.com/user-attachments/assets/1d20ddd8-7063-43c0-bbd7-f30b9a3748bd)

This is the result for adding to one switch.  
![image](https://github.com/user-attachments/assets/a8a2b565-6f51-457f-a8d1-8b5667387c4b)


## Proper Solution
Either fix the path to the built in 3D models AND CHECK THAT "H" IS CORRECT, or
add the Omeron file to the PCB footprint library part and safe with a new part number reflecting the Omron part number "B3F-1070"

**Comment by nk25719** [comment]
this is a

**Comment by nk25719** [comment]
This is a PMD issue and not Krake's.

**Comment by nk25719** [comment]
test email.

**Comment by ForrestErickson** [comment]
Adding Oyin to this issue.

Here is an OpenSCAD file with a candidate design:
[Switch_key_caps_WIthGirdel.zip](https://github.com/user-attachments/files/17829099/Switch_key_caps_WIthGirdel.zip)

![image](https://github.com/user-attachments/assets/dda0d9a2-4b6d-46c7-b29c-baee3a9359c5)

**Comment by ForrestErickson** [comment]
Moved to the upstream of the Homework2 repository at: 
https://github.com/nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-/issues/83

Closing.
