### ISSUE TITLE
Migrate_GPAD_Krake/ on a Branch

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#61]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 ## Summary
Practice Migrate_GPAD_Krake/ in a branch.  

### Steps
Put the new KiCad project into a folder called Migrate_GPAD_Krake.  
Save as the GPAD as Krake. 
Delete as many files as do not cause problem. 
Make initial commit at this stage.  Commit message "Migrate_GPAD_Krake initial commit"
Then, update the title blocks in the schematic and the PCB.
Make a commit.
Look for what is broken.

 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 
 Image of the reduced files after culling unnecessary files
![image](https://github.com/user-attachments/assets/50e9b3cd-1d8e-47d7-9ab7-8adab47ad37d)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
 
 
**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by nk25719** [comment]
Modified the .gitignore file to ignore the pattern "*-backups/"
