### ISSUE TITLE
Choose ESP32 Development Kit and / or Module for Krake PCB

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#63]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
From time to time Nagham and Lee have  become confused about the exact ESP32 with which we are designing.

There are multiple development kits available and ESP32 modules too.
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 
Choose from parts readily available at both JLCPCB and PCBWay as well as replacements from Digi-Key
![image](https://github.com/user-attachments/assets/084005c4-ae48-4eb5-ba61-01543908b9d1)

 From JLCPCB:
https://jlcpcb.com/parts/2nd/IoT_Communication_Modules/WiFi_Modules_80342?spm=search&searchTxt=esp32
![image](https://github.com/user-attachments/assets/576a9ea7-de13-4c0d-9293-c284f531e8d2)

**Comment by nk25719** [comment]
implementing ESP32-WROOM-32D in Krake's schematic 

<img width="375" alt="image" src="https://github.com/user-attachments/assets/9412e6aa-fcc5-417e-b6f4-e89630459088">
