### ISSUE TITLE
Add hearder footprint on every ESP32 pin for troubleshooting access.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#68]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 
 
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
 
 
**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by ForrestErickson** [comment]
Add single in line package header (SIP header) with 0.1" pitch around the ESP32 package to allow access to every pin for troubleshooting and contingency.

Here is an example from another PI project.  
Schematic   
![image](https://github.com/user-attachments/assets/2653f9c4-3ac2-45a7-a110-00d609e98ec6)

PCB  
![image](https://github.com/user-attachments/assets/41721f5d-decc-42a1-8063-170281aee569)  

3D Render  
![image](https://github.com/user-attachments/assets/4078e23f-15c1-4ee5-9645-6cbc6410612a)

**Comment by nk25719** [comment]
<img width="293" alt="image" src="https://github.com/user-attachments/assets/ad88c7d3-3a0b-491f-a580-26ff0b5505a4">

Adding headers for ESP32 module.

**Comment by nk25719** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/45343e6f-3664-473f-ae5c-6b707ad13ab5">
