### ISSUE TITLE
ESP32 Requires Reset and Boot Button Circuits from the Development Board

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#70]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
The ESP32 programing from the Arduino IDE requires the Reset and Boot circuit with the push buttons as per the ESP32 Development Kit board schematic.

**Comment by nk25719** [comment]
Added Reset and Boot button circuit

<img width="423" alt="image" src="https://github.com/user-attachments/assets/195ed23d-43bc-4592-bc30-0f623584d683">

**Comment by nk25719** [comment]
Added a boot switch 

<img width="427" alt="image" src="https://github.com/user-attachments/assets/b1f73fdb-980b-4f31-8ece-68712da34bcf">

cc: @ForrestErickson 

Closing.
