### ISSUE TITLE
Make a DF Player Footprint

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#77]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 the Df player needs a foorprint and maybe a 3d module as well.
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 create a df player module
create a df player 3d module

**Comment by nk25719** [comment]
### created a df player foot print 
the pins start from the top left corner and go in a unti clockwise dorection

approx dimensions : 
x-16.5  and y=19.2
and the sd card slot is represented by the silkscreen of measurement x-14.7 and y-14.5

<img width="691" alt="image" src="https://github.com/user-attachments/assets/29be970d-aae2-4716-8504-dc4a95193426">

**Comment by nk25719** [comment]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/58c02ca5-9fe0-4a2c-bcd6-48058bd2a603">

**Comment by ForrestErickson** [comment]
Review the schematic symbol (which I think is bad), the PCB footprint and the 3D model here:
https://www.snapeda.com/parts/DFR0299/DFRobot/view-part/

**Comment by ForrestErickson** [comment]
Regarding, "sd card slot is represented by the silkscreen of measurement x-14.7 and y-14.5"
Make the box hollow. Just make an outline.

Additionally the outline for and SD card when inserted should be added so that we can visualize the card location relative to the enclosure.

An SD card STEP file should be added to the 3D model too.

**Comment by nk25719** [comment]
link to dfplayer mini datasheet:
 chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.farnell.com/datasheets/3161923.pdf?_gl=1*xtvfhr*_gcl_au*MTQ0OTQzNzY5MS4xNzMxNjEwMjMy

**Comment by nk25719** [comment]
<img width="568" alt="image" src="https://github.com/user-attachments/assets/a15343c9-aa92-4347-a05e-8215529d9ea6">

**Comment by nk25719** [comment]
Path to DFPlayer Footprint: 
[PCBa_KRAKE/PCBa_KRAKE.pretty/DFPlayer_mini_20241116.kicad_mod](url)


Closing.
