### ISSUE TITLE
Code from v 0.15 requires ESP32 espressif  board to version 3.05

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/krake#79]
**Describe the bug**

In @ForrestErickson 's Arduino IDE, v.0.15 of the code failed to compile. By looking at included libraries, Rob concluded the new library included in V0.15 of the code must be in the "package" named "esp32 by Espressif Systems".  We learned that Lee was using the Version 2.X series, but Rob was on the latest 3.05 Version. 
 
After Lee upgraded to the 3.0.5 version, he was able to compile. 

 
 
**Screenshots**
![Screenshot 2024-11-14 at 7 05 31 PM](https://github.com/user-attachments/assets/c4c4d10a-68c3-48c4-9345-dd30be79ee11)

 
 
**Hardware description**
Model: Krake Homework device
Serial Number:  Austin 
Other:

**Comment by RobertLRead** [comment]
@nk25719 @ForrestErickson I am assigning to Nagham only as an "For Your Information (FYI)" courtesy in case she has trouble with this. We need to all be on the same library versions, and unfortunately the Arduino IDE makes that somewhat difficult.

Nagham and Lee should close this issue when they can both successfully compile.

**Comment by nk25719** [comment]
As of 20241119 Nagham compiled and uploaded software version 0.19


Closing.
