### ISSUE TITLE
MQTT Connection Lost & Not Recover, Processing PMD and GPAD_API V0.17

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#82]
## Describe the bug
_A clear and concise description of what the bug is._
Short Summary of the expected behavior:  MQTT Connection to recover after waking the PC from sleep.
Short Summary of the buggy behavior:  The Processing PMD lost connection and when restarted still not successfully publishing to nor receiving keepalive subscriptions from GPAD_API V0.17 devices.
The four Homework2 GPAD_API V0.17 devices appear to be locked up (not running program).
 
 
### Detailed Description PMD

Was running the Processing PMD on Lee's PC overnight. 
The PC went to sleep
Restart PC
The Processing PMD console reported connection lost (As it has every other day before)
Today 20241117 restarting the program did not restor connection.

The draw window starts up grey but then goes green when the MQTT connection to broker is made.
In the draw windows the background is green because no packets are received from the broker.
![image](https://github.com/user-attachments/assets/25209227-0720-4bbc-a5c2-6892741fe9e9)

There remains no messages to which the PMD is subscriving.
![image](https://github.com/user-attachments/assets/622b9211-13cf-460b-a2f5-a6bcf4de8df7)

Using Wireshark Lee found the outgoing MQTT topic with messages to the broker for the five USA devices such as KRAKE_20240421_LEB5_ALM
![image](https://github.com/user-attachments/assets/83b10a9b-2443-46a9-be4b-a8713092e8e2)

However there is no traffic back from the broker with expected MQTT topics such as KRAKE_20240421_LEB5_ACK

### Detailed Description GPAD_API on Homework2
There are four Homework2 assemblies running in Maryville TN
The three Homework2 assemblies with LCD are showing alarm level 5. The single device with out LCD has not alarm LEDs lit.
None of the heart beat LEDs are blinking.
None of the keep alive message LEDs are blinking.
Device USA1 has no alarm LEDs lit.  Heart beat and keep alive LED are lit.
Device USA2 has all alarm LEDs lit.  Heart beat and keep alive LED are lit.
Device USA3 has no alarm LEDs lit.  Heart beat is lit and keep alive LED is off.
Device USA4 has no alarm LEDs lit.  Heart beat and keep alive LED are lit.  This device has no LCD.

Lee opened the serial port connection to USA3 and saw a single message for a reconnection attempt to the broker
![image](https://github.com/user-attachments/assets/ad01479d-129b-4e61-8c52-77f685d5da6a)

### Capture Network Status on Lee's Network at morning of failure
Did an arp -a to see recently active IP addresses
![image](https://github.com/user-attachments/assets/a9928c74-498a-4f5b-bde5-47c19e5957bc)

Ran a PING to broadcast IP addess to make the arp list big.
![image](https://github.com/user-attachments/assets/e499cf03-4be1-4ec0-bc14-cdcb60233481)

Results of arp -a after the broadcast ping.
![image](https://github.com/user-attachments/assets/2f1ec389-78db-4bf4-b70f-6510761e916e)

**Comment by ForrestErickson** [comment]
About 8:20 Lee power cycled the router and  now all four devices are connecting to the WiFI.

HOWEVER what I have learned is that when the WiFi connection can not be made the GPAD_API V0.17 gets hung up trying to make an impossible MQTT connection.

**Comment by RobertLRead** [comment]
I believe this is fixed in verison 0.19. I institued a fixed number of retries.
