### ISSUE TITLE
Hardware, Delete the I2C connector inheretted from GPAD

### ISSUE THREAD

**Issue by nk25719** [PubInv/krake#91]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
J105,  I2C connector creates a layout congestion for the I2C bus. There is no use case for this connector for the KRAKE (and there never was for the GPAD either.) Additionally it occupies layout area which we need to repurpose for the rotary encoder. 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Remove J105 and R105 and R104 and C113 and C114
 
 
**Additional context**
_Add any other context or screenshots about the feature request here._

<img width="400" alt="image" src="https://github.com/user-attachments/assets/04f40bc2-c6cb-4ad9-bdc7-6734f88a4518">

**Comment by nk25719** [comment]
<img width="401" alt="image" src="https://github.com/user-attachments/assets/eb813662-477b-4bba-81da-2a80b7a20c77">

highlighting the I2c connections that should be removed.

**Comment by ForrestErickson** [comment]
@RobertLRead 
It is important that you **consent** to this change.
Please review. I understand if you want to speak about it too as there is undocumented history and perhaps not common understanding on all our parts.
Lee

**Comment by RobertLRead** [comment]
I do consent to this. @ForrestErickson @nk25719 

I feel like I2C is unlikely to be a useful protocol for the Krake; supporting SPI and a serial interface should be enough.

**Comment by nk25719** [comment]
From:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/efcbc94d-0b2b-4cd7-bc1b-77678b6b55c2" />





To :

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ce9cd6af-ed01-490a-9cb8-167c43da334d" />
