### ISSUE TITLE
Hardware, Optimizes EN (nRESET) Rise Time, ESP32

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#92]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 Products with poorly designed nRESET often malfunction dueo to short power interuptions.

 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 A reset circuit which delays EN till the ESP32 is stable.
A reset circuit which follows Vcc down so that it is ready to make the required delay when power returns.
 
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
The GPAD has a schottky diode to discharge the reset capacitor.  
 
**Additional context**
_Add any other context or screenshots about the feature request here._

This is the EN (nRESET) waveform from an ESP32 Dev1 Kit
![image](https://github.com/user-attachments/assets/dc753ca2-f127-41e8-b5be-00d84bbf69e3)

**Comment by ForrestErickson** [comment]
The GPAD reset circuit with capacitor to nRTS.
![image](https://github.com/user-attachments/assets/e1d3e141-1a2d-415a-be61-ef21c9b053ff)

**Comment by nk25719** [comment]
R102 and Diode D103 must be connected to 3v3 same as the ESP32

**Comment by nk25719** [comment]
Capturing the nReset circuit. 
A 330 ohm resistor was inspired by the HILetGo schematic.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/8c521a56-36de-4978-838f-9e42fa7a0844" />
